# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Florian Schoppmann
email: mail@florian-schoppmann.net
description: > # this means to ignore newlines until "baseurl:"
  Florian Schoppmann’s professional and academic work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://florian-schoppmann.net" # the base hostname & protocol for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - '*.iml'
  - README.md
opengraph:
  image: "https://florian-schoppmann.net/assets/img/florian-opengraph.jpg"
  type: website

kramdown:
  input: GFM
